import { SupabaseClient } from '@supabase/supabase-js';

/**
 * Marks pending installments (payments) for a student as 'paid' 
 * based on the amount received from a payment gateway webhook.
 * 
 * It iterates through chronological pending payments and marks them
 * as paid until the webhook amount is exhausted.
 */
export async function syncGatewayPaymentToInstallments(
    supabase: SupabaseClient,
    studentId: string,
    saleId: string,
    amountReceived: number,
    gateway: string
) {
    if (!studentId || !saleId || amountReceived <= 0) return;

    // 1. Fetch pending payments for THIS specific sale ordered by due date
    const { data: pendingPayments, error: fetchError } = await (supabase
        .from('payments') as any)
        .select('*')
        .eq('student_id', studentId)
        .eq('sale_id', saleId)
        .eq('status', 'pending')
        .order('due_date', { ascending: true });

    if (fetchError || !pendingPayments || pendingPayments.length === 0) {
        console.warn(`No pending payments found for student ${studentId} to cover ${amountReceived} from ${gateway}. Will create standalone history record.`);
    }

    let remainingToCover = amountReceived;
    const updates = [];

    // 2. Iterate and mark as paid if there are pending payments
    if (pendingPayments && pendingPayments.length > 0) {
        for (const payment of pendingPayments) {
            if (remainingToCover <= 0.05) break;

            if (remainingToCover + 0.05 >= payment.amount) {
                updates.push({
                    ...payment,
                    status: 'paid',
                    method: gateway,
                    paid_at: new Date().toISOString(),
                    updated_at: new Date().toISOString()
                });
                remainingToCover -= payment.amount;
            } else {
                break;
            }
        }
    }

    // 3. Persist updates for existing pending installments
    if (updates.length > 0) {
        const { error: updateError } = await (supabase
            .from('payments') as any)
            .upsert(updates);

        if (updateError) {
            console.error(`Failed to update installments as paid for student ${studentId}:`, updateError);
        } else {
            console.log(`✅ Marked ${updates.length} installments as paid for student ${studentId} via ${gateway}`);
        }
    }

    // 4. Create an 'orphan' paid installment for any remaining amount.
    // This provides a permanent visual ledger entry in the UI if there were no installments generated by the admin, 
    // or if the student paid more than what was currently pending.
    if (remainingToCover > 0.05) {
        const insertPayload = {
            student_id: studentId,
            sale_id: saleId,
            amount: remainingToCover,
            status: 'paid',
            due_date: new Date().toISOString().split('T')[0], // Today
            method: gateway,
            paid_at: new Date().toISOString(),
            notes: 'Pago recibido (autogenerado)',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
        };

        const { error: insertError } = await (supabase
            .from('payments') as any)
            .insert(insertPayload);

        if (insertError) {
            console.error(`Failed to insert visual history record for student ${studentId}:`, insertError);
        } else {
            console.log(`✅ Inserted visual ledger record of ${remainingToCover}€ for student ${studentId} via ${gateway}`);
        }
    }
}
